# Generated by Django 3.1.5 on 2021-01-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0002_auto_20210119_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=1000)),
                ('website', models.CharField(max_length=1000)),
            ],
        ),
    ]
